### ISSUE TITLE
iOS 15 multiple performBatchUpdates causes an animation problem

### ISSUE THREAD

**Issue by zendesk-benabu** [ekazaev/ChatLayout#22]
On the last release of the Chatlayout this issues was address but not really fixed.
In-fact in the example all actions are added one after the other. The way we use the library involves several changes at the same time. 

**Step to reproduce:**
Have two different actions in the same operation like: remove a message and add a new one.
To simulate that I have updated the `sendMessage` function in `DefaultChatController` in line 63 by adding the following code:
`if !messages.isEmpty { messages.removeLast() }`

So now when you send a message it will delete the last message in the conversation at same time.
The `StagedChangeset` is a collection that now have two operations which involve two `performBatchUpdates`
![Sep-30-2021 14-22-31](https://user-images.githubusercontent.com/90382882/135454123-e97bc607-fbcd-48de-b76f-5287809e0355.gif)

I'm opening this pull request to suggest a solution and open the discussion to that.
[https://github.com/ekazaev/ChatLayout/pull/21](https://github.com/ekazaev/ChatLayout/pull/21)

**Comment by ekazaev** [comment]
@zendesk-benabu Hi. Thank you for the issue. Yeah. It’s another tale as long as time. I hoped that apple will fix what they broke in the final release of ios 15 (how could they fecked up that math that worked fine since ios 6i don’t understand), but it seems they are not going to. So it has to be handled on the client side. I’ll examine your PR a bit later and come back to you.

**Comment by zendesk-benabu** [comment]
Thank you @ekazaev. It's annoying, maybe we need to report the issue to Apple. 
However it may be wanted in order to use the new iOS15 `reloadItems` api.

**Comment by ekazaev** [comment]
@zendesk-benabu 
I think I managed to avoid that strange extra call.
Can I ask you to play around with origin/feature/fix_ios15 branch. Especially it will be help-full in you real project.

**Comment by ekazaev** [comment]
@zendesk-benabu I tested on the available devices and simulators and it seems to be fine. I close the issue. Thank you again.
