### ISSUE TITLE
Getting many prints of 'UICollectionViewRecursion' not sure what it means

### ISSUE THREAD

**Issue by brunomunizaf** [ekazaev/ChatLayout#23]
Hello again! :)

I'm getting a lot of prints of the following message: 
```[UICollectionViewRecursion] cv == 0x7ff0518ece00 Disabling recursion trigger logging```
But I have no idea what is it about. After a quick google search It seems related to compositional layout on iOS 15 maybe? Do you have any idea what is going on? 

Just for sake of more clarity (if any) it prints when dequeueing the cells for the first time and all memory addresses are the same

Cheers!!

**Comment by ekazaev** [comment]
@brunomunizaf Id suggest not to worry much about it for now. It seems that its apples internal problem. Looks like SwiftUI also causes it without even referencing the UICollectionView. 
https://stackoverflow.com/questions/69397650/swiftui-disabling-recursion-trigger-logging-when-use-menu
Well, I assume that apple uses UICollectionView to draw the Menu itself. But Ill keep my eye on it. A bit busy this days.

**Comment by ekazaev** [comment]
Ok, a lady from apple confirmed that its their logging that wasn't disabled. Dont worry about it. 
https://twitter.com/caughtinflux/status/1439276097464528896?s=21
