### ISSUE TITLE
Translation button break the UI

### ISSUE THREAD

**Issue by zendesk-benabu** [ekazaev/ChatLayout#24]
On iOS15 Apple added a new `Translate` button in the `uiMenuController`.
Step to reproduce:
Select the text from the input bar and click to translate, then close the bottom sheet 
Result: The `ChatViewController` will scroll up and the input bar will be removed:
![translation](https://user-images.githubusercontent.com/90382882/136419855-7595cd57-45b4-403d-b533-ce5859ae7f70.gif)

**Comment by ekazaev** [comment]
OMG. Ill have a look. Thank you.

**Comment by ekazaev** [comment]
@zendesk-benabu What I can tell you for now. It seems everyone who displays inputView has this issue one way or another. I checked other libraries. It looks like another big hello from ios 15.
