### ISSUE TITLE
Huge bottom space and weird behavior for 1.1.11

### ISSUE THREAD

**Issue by aplr** [ekazaev/ChatLayout#26]
Hi, some issues popped up with your lib. Up until 1.1.10 my app behaved fine, but as soon as I've upgraded ChatLayout to 1.1.11, things got flaky. When entering a chat room, a huge chunk of empty space without any chat message cells is shown. When looking into layout inspector, no cells show up within the collectionView. When scrolling up, some chat message cells appear, but when scrolling back down they start to disappear again. I first thought it is some autolayout issue (which it could still be), but it worked pre 1.1.11, so I thought I want to ask you here if you know what the issue could be.

![trim 99C16C45-89F9-4ABF-98F9-6EC81DEFBCE1](https://user-images.githubusercontent.com/1051396/137886714-c3f2b0e1-327d-4af4-985d-999f7fc57515.GIF)

Thank you, and it's a really cool library you have here!
Andreas

**Comment by aplr** [comment]
Noo by no means, I'm just not using the cells from your demo app. But overall, they behave exactly like the ones in iMessage. Seems like an interesting topic, I'll also check the code changes you did, seems like it's not too much. Maybe it is also some instability due to autolayout issues in the first place, and the old way of searching for visible cells was more resilient to them?

**Comment by ekazaev** [comment]
@aplr Do you use sections in your code?
