### ISSUE TITLE
NSInternalInconsistencyException

### ISSUE THREAD

**Issue by iBachek** [ekazaev/ChatLayout#27]
Hi, thank u for the new chat behaviour.

I faced with crash on your example app, you can reproduce it, if replace your code in `DefaultChatController`

Reason: invalid number of sections. The number of sections contained in the collection view after the update (170) must be equal to the number of sections contained in the collection view before the update (89), plus or minus the number of sections inserted or deleted (0 inserted, 1 deleted).

change `line 147`
```swift
DispatchQueue.main.async { [weak self] in
    guard self != nil else {
        return
    }
    completion([Section(id: 0, title: "Loading...", cells: Array(cells))])
}
```

to
```swift
DispatchQueue.main.async { [weak self] in
    guard self != nil else {
        return
    }

    let sections = Array(cells).map { cell in
        Section(id: cell.differenceIdentifier, title: "New Section", cells: [cell])
    }

    completion(sections)
}
```

**Comment by ekazaev** [comment]
@iBachek Morning. I am not sure why you did that modification in the first place - you wrapped each cell into a section. The Example app doesn't support more then one section. If you need more then one section - you will have to modify the entire app.

PS: About supplementary views in general see https://github.com/ekazaev/ChatLayout#about-supplementary-views

**Comment by iBachek** [comment]
@ekazaev section header header has a visibility behavior when scrolling and snapping to the top, this is necessary to separate messages by date

**Comment by iBachek** [comment]
> @iBachek Morning. I am not sure why you did that modification in the first place - you wrapped each cell into a section. The Example app doesn't support more then one section. If you need more then one section - you will have to modify the other parts of the app.
> 
> PS: About supplementary views in general see https://github.com/ekazaev/ChatLayout#about-supplementary-views

what parts do you mean?

**Comment by ekazaev** [comment]
Firstly. This doesnt discount my comment above. If you want to have more then one section - you need to modify the rest of the app. 

Secondly: Snapping header to the top is not supported by the layout itself. So if you need this behavior you'll need to implement it yourself. My assumption is that you need to create a fake date view at the top of the container view that will hold your collection view and track the visibility of the date cell within the collection view and if it is above the top boundary of the collection view - make your fake date view visible.

See also https://github.com/ekazaev/ChatLayout/issues/18

**Comment by ekazaev** [comment]
About what parts to modify: At least you need to comment out the scrolling to the last item in ChatViewController line 470 as there is an incorrect calculation. Then it should work:
![Screenshot 2021-12-14 at 10 22 29](https://user-images.githubusercontent.com/20243258/145980149-d575c29f-194e-4413-b742-0b66d2eae9e2.png)
Then you need to fix your code in the way you are currently using difference identifier for the section. In your current variant you are making update operations over entire section. Basically you reload entire section with all the cells inside and and its headers and footers. So you will see small jumps in the UI.
