### ISSUE TITLE
First message question

### ISSUE THREAD

**Issue by akaraul** [ekazaev/ChatLayout#28]
Hi!
How can I make it so that when I send the first and following messages in the chat, they are at the bottom of the screen?
Like Telegram, for example...
![Simulator Screen Shot - iPhone 13 - 2022-04-22 at 16 19 04](https://user-images.githubusercontent.com/20819174/164722257-21b5a4f8-ff3c-4831-a1f7-5eb291294b39.png)

**Comment by ekazaev** [comment]
@akaraul Hi

Such behavior is not currently supported. The layout behaves like iMessage app or Whatsapp. To support such behavior it is requires to modify the layout itself. I may add it someday but cant guarantee that it is going to happen any time soon. Feel free to modify the layout yourself if you are in a rush and I will appreciate the PR.

**Comment by ekazaev** [comment]
Closed due to inactivity
