### ISSUE TITLE
Sometime message of sender show to left

### ISSUE THREAD

**Issue by anhhtbk** [ekazaev/ChatLayout#29]
Sometime message of sender show to left, after scroll it show to right
![IMG_0423](https://user-images.githubusercontent.com/17321700/167110949-805b337e-d4d5-4804-a96e-18490efee798.jpg)

**Comment by ekazaev** [comment]
@anhhtbk Thank you. Can you provide some steps to reproduce? Also what ios version is it?

**Comment by anhhtbk** [comment]
I clone again and it is normal, maybe I do something wrong.
