### ISSUE TITLE
Sticky headers

### ISSUE THREAD

**Issue by akaraul** [ekazaev/ChatLayout#30]
Hi! How we can implement sticky headers? It's not possible now?

**Comment by akaraul** [comment]
@Frizlab thanks! I will check your fork

**Comment by Frizlab** [comment]
Forgot to say, the branch in the fork with my work is `frizlab`: https://github.com/Frizlab/STableLayout/tree/frizlab

**Comment by ekazaev** [comment]
@Frizlab @akaraul I played around with the sticky headers and I came across similar issues. Id suggest to implement sticky headers without relying on the collection layout. I assume you want to use them for dates. I did some thing like that unrelated to the chat layout. And it was possible by listening UIScrollView events directly and adding views directly to the UICollectionView

**Comment by akaraul** [comment]
Ok, thanks

**Comment by ekazaev** [comment]
@Frizlab Do you have some branch that demoes your implementation of sticky headers? I checked out your project but I cant see anything in the Example app

**Comment by Frizlab** [comment]
I did not. Just for you I created the `dev.demo` branch (which I might merge at some point in `develop`).
😉

**Comment by Frizlab** [comment]
**Note**: I have a bug where a pinned item won’t push the previous pinned item when it becomes pinned. Section headers are properly pushed.
I workaround the bug in the example by playing with the `zPosition` of the date cells (which I had to do anyway because they had to be above the normal cells).

**Comment by ekazaev** [comment]
Thank you @Frizlab Ill check your code when ill have more time. I also have a branch with sticky headers experiments, but I also did not completely succeeded there. Dont hesitate to ping me if youll have a proper solution.

Ill close this issue for now as sticky headers were never advertised as a feature. But they are doeable for sure above the collection layout level.
