### ISSUE TITLE
Chat doesn't correctly scroll to bottom after receiving a new message on iOS 16

### ISSUE THREAD

**Issue by IAmConorNolan** [ekazaev/ChatLayout#33]
On iOS 16, the collection view doesn't correctly scroll to the bottom after receiving a new message.

Affected: All beta versions of iOS 16. 

## Expected Behavior

If the user is scrolled to the bottom of the collection view.
When they receive a new message
They collection view should scroll down to show the new message

## Current Behavior

If the user is scrolled to the bottom of the collection view.
When they receive a new message
The collection view doesn't scroll

https://user-images.githubusercontent.com/52077255/185611149-350893be-9542-41d7-871c-f7d9892f058f.mov

## Possible Solution

Investigating, but no suggested fixes as of yet.

## Steps to Reproduce

1. Open the ChatLayout example on an iOS 16 simulator.
2. Scroll to the bottom.
3. Wait for new messages to arrive.
4. Observe that they do not scroll to the correct item.

## Context (Environment)

This leads to a broken experience on iOS 16.

**Comment by ekazaev** [comment]
@IAmConorNolan Hi, Thank you for the issue.

Yep, I also noticed it in the latest IOS 16 beta. I remember testing the layout in one of the first betas and it was allright. Can you please test latest version 1.2.4 and confirm that the bug is gone.

Regards,
Eugene

**Comment by ekazaev** [comment]
@IAmConorNolan I am closing the issue due to incativity. If the new version did not solve your issue - feel free to reopen it

**Comment by IAmConorNolan** [comment]
@ekazaev I can confirm this version resolved the issue. Thank you!
