### ISSUE TITLE
Weird update animation of the cell

### ISSUE THREAD

**Issue by nugmanoff** [ekazaev/ChatLayout#38]
Hey @ekazaev! Thanks for all the hard work you have done to make this thing work!
And without your Example app – we'd be lost as well. It is a huge source of inspiration and foundation to start building on.
I am yet founding my way around the library and all of the smart tricks you implement in example app. 

There is one particular issue that I am facing right now when performing the updates, here is the demo:

https://user-images.githubusercontent.com/20473743/199419075-37a6b7f0-a27c-4469-8dd7-35e71a35a660.mp4

Reproduction steps:

1. When user presses **send** button, message gets immediately added to the in-memory array of messages and they are propagated. Everything as like in your example app.
2. At the same time message is send to the server (transport is not important, but for the sake of completeness it is websocket connection). It happens in the same method as adding to the in-memory array.
3. After receiving the message server pings broadcasts back the freshly sent message back to the client. It has the same exact id, text and all other values except for **date**. Because server overrides the message timestamp with the newer one.
4. Upon receiving this *slightly updated* message I call `func received(messages: [RawMessage])`, just as you did in example app. 

And at this point I expect for the last message to just smoothly update its timestamp. But what happens the old version of cell jumps all the way to the top while fading away at the same time, and new message inserted from the bottom. You could see that from the video I attached.

![CleanShot 2022-11-02 at 12 42 45](https://user-images.githubusercontent.com/20473743/199424694-96baa977-9258-40c9-8633-ad701443c6d7.png)

In the attached screenshot you can see the debugger breakpoint with corresponding prints of:
- `messages.last` which is esentially the message that was appended to the in-memory array
- `rawMessages` which is an array of size 1 of newly received messages from the server, which is the same message but with the updated timestamp. You can see that they have the same ids, and only the date is different.

I don't understand why the jump happens.

I hope that I explained my case with sufficient details. Let me know if I need to provide more input.

**Comment by ekazaev** [comment]
Hi @nugmanoff 

Thank you for the nice words. Happy to see that the issue is resolved. Best of luck.

Eugene
