### ISSUE TITLE
How to make collectioview show messages immediately

### ISSUE THREAD

**Issue by Sabellus** [ekazaev/ChatLayout#40]
What needs to be done so that when the chatviewcontroller push-navigates, the data is already ready?

An empty collection is shown. then messages? Like no spawn animation.

i played with it

`collectionView.contentInsetAdjustmentBehavior = .always`

changed to this

`collectionView.contentInsetAdjustmentBehavior = .never`

then the collection of elements is loaded immediately

but there are a number of artifacts associated with tabbar navigation and inputAccessoryView

inputAccessoryView twitches and disappears and reappears 2 times

I attach screenshots

![IMG_7545](https://user-images.githubusercontent.com/24656120/207018000-b435f87f-e673-4c4c-ab14-ffe0b5678641.PNG)
![IMG_7546](https://user-images.githubusercontent.com/24656120/207018027-62c50855-4667-4499-992d-3146c3ec0028.PNG)
![IMG_7547](https://user-images.githubusercontent.com/24656120/207018039-7f78016c-77bb-4754-96fd-1257970d41c3.PNG)

please help me how to do this, thanks

**Comment by Sabellus** [comment]
What exactly should I do?
1. remove
```
    override var inputAccessoryView: UIView? {
        inputBarView
    }

    override var canBecomeFirstResponder: Bool {
        true
    }
```
2. adding and change
```
    view.addSubview(inputBarView)
    inputBarView.bottomAnchor.constraint(equalTo: self.view.keyboardLayoutGuide.topAnchor).isActive = true
    collectionView.bottomAnchor.constraint(equalTo: inputBarView.topAnchor, constant: 0),
```

3. where to add this: `let keyboardOffset = max(0, view.safeAreaLayoutGuide.layoutFrame.maxY - view.keyboardLayoutGuide.layoutFrame.minY)`
```
func keyboardWillChangeFrame(info: KeyboardInfo) {
        guard !currentInterfaceActions.options.contains(.changingFrameSize),
              collectionView.contentInsetAdjustmentBehavior != .never,
              let keyboardFrame = collectionView.window?.convert(info.frameEnd, to: view),
              keyboardFrame.minY > 0,
              collectionView.convert(collectionView.bounds, to: collectionView.window).maxY > info.frameEnd.minY else {
            return
        }
        currentInterfaceActions.options.insert(.changingKeyboardFrame)
        let newBottomInset = collectionView.frame.minY + collectionView.frame.size.height - keyboardFrame.minY - collectionView.safeAreaInsets.bottom
        if newBottomInset > 0,
           collectionView.contentInset.bottom != newBottomInset {
            let positionSnapshot = chatLayout.getContentOffsetSnapshot(from: .bottom)

```


4. setupInsets() what is there?
    eventHandler  what is there?
```
     private var isFirsAppearance = true
     override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()

        // Hack to prevent animation of the contentInset of first appearance. The same is used in MessageKit
        if isFirsAppearance {
            isFirsAppearance = false
            setupInsets()
            let initialCells = eventHandler.getInitialCells()
            if !initialCells.isEmpty {
                processUpdates(with: initialCells, animated: false, ignoreInterfaceActions: true)
            }
        }
     }
```

**Comment by ekazaev** [comment]
@Sabellus Yep you understand in general fine. But you should understand I am giving you a theoretical code. I can not write it for you. I can only give you some directions.

`evenHandler` in this case something that will return initial cells in the collection view
`setupInsets` looks something like

**Comment by Sabellus** [comment]
Appreciate your help! It works ❤
