### ISSUE TITLE
Cannot installed with Carthage

### ISSUE THREAD

**Issue by tangzzz-fan** [ekazaev/ChatLayout#41]
Hi, team.
I'm trying to integrate the xcframework of this project via Carthage but it fails on command line compilation.

Please help me with this issue.

**Comment by tangzzz-fan** [comment]
“./carthage.sh update --platform iOS --no-use-binaries --use-netrc --use-xcframeworks” script is used.

**Comment by ekazaev** [comment]
Hi @tangzzz-fan I ll have a look after the holidays, but I can not guarantee you a resolution here. I was actually planning to discontinue supporting cathage as it has too many issues in general.

**Comment by tangzzz-fan** [comment]
OK, Thanks for providing this excellent framework. According to your roadmap, I will integrate this framework in a manual way.

**Comment by ekazaev** [comment]
@tangzzz-fan Hi and happy new year. Can you please try carthage again with the latest version 1.2.15

**Comment by tangzzz-fan** [comment]
> @tangzzz-fan Hi and happy new year. Can you please try carthage again with the latest version 1.2.15

It's OK, with v1.2.15. 
Thanks for your quick response.

**Comment by ekazaev** [comment]
Perfect, best of luck
