### ISSUE TITLE
General Question UITableView  vs UICollectionView

### ISSUE THREAD

**Issue by alexookah** [ekazaev/ChatLayout#42]
Hi,
I read your blog post about how you managed to create this Library. I am not fully convinced why someone should use `UICollectionView` instead of `UITableVIew`. I know `UICollectionView` has more features & power to customise e.t.c. But I would really like your opinion why someone should use `UICollectionView` instead of `UITableView` which handles very nice the autolayout calculations.

**Comment by ekazaev** [comment]
Hi @alexookah 

Id say overall if `UITableView` fits your needs - use it - there is nothing wrong with it. But it has natural limitations. Like you can not make `UITableView` scroll horizontally for example. Otherwise a `UICollectionView` or something absolutely custom within a `UIScrollView` is your only choice.

**Comment by alexookah** [comment]
Thanks for taking time to answer this.
Could you list some things you think that are not achievable with UITableView?

**Comment by ekazaev** [comment]
@alexookah 
There are few to start:
- Try to insert/reload/delete cell/(multiple cells) and and keep the visible content offset of the `UITableView` at the bottom.
- Try to create N(big amount like 10000) table view cells of the unknown size, lets say populate them with a random string and use auto-layout and try to make it present last cell on appearance.

**Comment by ekazaev** [comment]
@alexookah Anything else you would like to ask or I can close the issue?

**Comment by ekazaev** [comment]
@alexookah I am closing the issue. Feel free to reopen it if you have more question
