### ISSUE TITLE
How to design the structure of clicking the message to jump to the next page?

### ISSUE THREAD

**Issue by std-s** [ekazaev/ChatLayout#48]
@ekazaev  hi,
How to design the structure of clicking the message to jump to the next page?

For example:
Click on the profile picture to jump to the Profile page. I don't know how to design it without breaking the architecture.

**Comment by ekazaev** [comment]
@std-s Hi,

Thank you for the question. I dont know your architecture. If we assume that you copied and modified the code from the example project - I would add a tap gesture recognizer to the avatar view and create a delegate in that view.  You can assign this delegate in the colelction view's data source to some object that knows how to present a profile view.

**Comment by ekazaev** [comment]
@std-s Ill close the issue. Fill free to reopen the issue if you have further questions.
