### ISSUE TITLE
Bottom offset keeping issues

### ISSUE THREAD

**Issue by nepodm** [ekazaev/ChatLayout#52]
Hi @ekazaev and thanks for the great chat layout solution!

I'm facing the issue with keeping collection view content at bottom position. Given `restoreContentOffset` in UIView.animate block makes top cells disappear like on the video below.

https://github.com/ekazaev/ChatLayout/assets/86278804/b9eb5bee-96ab-458a-8296-71966880b2d5

I was able to fix this behaviour by trying `scrollRectToVisible`, `scrollToItem` and `setContentOffset` (they give same result). Now top cells are not disappearing but if collection isn't at bottom position when batch updates starts it scrolls to bottom item for its estimated height only:

https://github.com/ekazaev/ChatLayout/assets/86278804/67183e35-8753-4ce9-9afc-0bc50a5ea7b9

I saw similar issues in this repo but there was no solution for my case. Can you help me to figure it out?

**Comment by ekazaev** [comment]
@nepodm hi

i am on vacation atm but ill be back soon. Can you please modify the example app to reproduce the behavior so I could have a proper look when i am back?

**Comment by nepodm** [comment]
I found the cause of the bottom offset scroll problem. I was trying to scroll to bottom item with unknown height (the item was never displayed and its height was not calculated). It can be fixed with scrolling to item with known height (like footer in your example project). I added zero height footer and scrolled to its bottom, this solved my first problem but now i have the second one.

When collection view content offset is updating with no animation it causes cell disappearing like on the video below:

https://github.com/ekazaev/ChatLayout/assets/86278804/cf828791-2296-4426-a48d-3d4e137c1f80

https://github.com/ekazaev/ChatLayout/assets/86278804/a75e2419-be1d-427a-b430-d059c50a7453

I saw [issue #43](https://github.com/ekazaev/ChatLayout/issues/43) but your demo code does not set offset properly in example project.

I overridden bounds of UICollectionView with `didSet` and now content offset is being set normally.

    final class ChatMessageCollectionView: UICollectionView {
    private var contentOffsets: [CGFloat: CGFloat] = [:]
 
    // keeps collection view content
    // offset on bounds change
    override var bounds: CGRect {
        didSet {
            let maxContentOffsetY = max(-contentInset.top, contentSize.height - bounds.height + contentInset.bottom)
            let previousHeight = oldValue.height
            let actualHeight = bounds.height
            
            contentOffsets[actualHeight] = contentOffset.y
            
            guard
                let previousContentOffsetY = contentOffsets[previousHeight],
                contentSize.height > actualHeight,
                previousHeight != actualHeight
            else {
                return
            }
            
            let visibleContentHeight = contentSize.height - previousContentOffsetY - previousHeight
            var offsetY = contentSize.height - visibleContentHeight - actualHeight
            
            offsetY = offsetY < 0 ? 0 : offsetY
            offsetY = min(maxContentOffsetY, offsetY)
            
            contentOffset = .init(x: 0, y: offsetY)
        }
    }
    }
    
    
    
But when im trying to animate contentOffset setting with `setContentOffset(.init(x: 0, y: offsetY), animated: true)` cells start flickering and jumping. Can you test this behaviour in your example project?



https://github.com/ekazaev/ChatLayout/assets/86278804/65fb79d8-deac-483e-a79b-1045fc19244b

**Comment by ekazaev** [comment]
@nepodm Hi. 

I am strugnling to understand what you are trying to achieve. Lets start from the beginning. So do you want that when the keyboard appears chat view scrolls to the last message?

**Comment by nepodm** [comment]
As I wrote above the problem with bottom scrolling is solved. 

Now i just want to keep collection view content offset during keyboard height updates without visual glitches. In your example app content offset of collection updates instantly. It causes cell disappearing (videos 121212.mov and Untitled.mov). Im trying to animate it with setContentOffset(animated: true) but bottom cells flickering (111.mov).

These are two different problems connected with thread theme.

**Comment by ekazaev** [comment]
@nepodm Lets talks about Example app as i dont see your code. In my app it sets without animation as it is considered as an acceptable behavior. Similar code is used in some apps in production and the issue didn’t bother anybody it seems. But there are always some tradeoffs.  

Some problems I assume you are hitting when using setContentOffset animated are described here: https://dasdom.dev/scrolling-a-collection-view-with-custom-duration/ I would suggest to use CADisplayLink based solution to get the consistent result.

**Comment by nepodm** [comment]
@ekazaev Thanks a lot for provided links and information. I never noticed this behaviour in WhatsApp app but now i see it. Meanwhile Telegram avoided that kind of cell disappearing problem somehow. My app has bigger header and input heights so it's much easier to observe. I will try described method and come back to this thread.
