### ISSUE TITLE
Incorrect chat layout frame when running on iOS 17

### ISSUE THREAD

**Issue by donnywdavis** [ekazaev/ChatLayout#54]
Hello. 🙂

We were running our existing app, that is built with Xcode 14.3, on iOS 17 to check for any bugs until we can switch to Xcode 15 and I noticed some weird behavior with the chat layout. When the `sizeForItem` delegate method is called, the `chatLayout` always has a width of 24. When running on iOS 16 it has the correct width of 366. I'm using the iPhone 14 for both scenarios. When building with Xcode 15 and running on iOS 17, there is no issue and we get the correct values.

I was curious if there might be something that I'm missing to try so that our builds using Xcode 14 will work correctly until we can start using Xcode 15?

**Comment by ekazaev** [comment]
@donnywdavis 
Hi. I dont fully understadn the issue you are expecting. 
> When the sizeForItem delegate method is called, the chatLayout always has a width of 24. 
Are you talking about `chatLayout.layoutFrame.width` that is passed to that function or what? I checked the scenarion you are describing and It seems everything is correct:
<img width="987" alt="Screenshot 2023-09-12 at 11 00 25" src="https://github.com/ekazaev/ChatLayout/assets/20243258/ff8fa68d-03a0-4ba7-8b53-af31824f1a4e">

**Comment by donnywdavis** [comment]
Hey @ekazaev,

Yeah, I am always seeing an incorrect frame size for `chatLayout.layoutFrame.width` when `sizeForItem` is called. This only happens on the first launch of the screen. If we send a message and reload the screen, then it gets the correct frame for all new cells that are added. But the previous cells are still broken.

To work around this for now, I am using a hard coded width value if it is less than 200. Randomly picked that value based on the SE device size. If the chat layout frame is greater than that, then it will use that value instead. This seems to be working so far. 

As I mentioned, building with Xcode 15 fixes the issue for me. So I don't see any need for any urgent changes. Mainly wanted to mention it in case there was some issue somewhere. But looks like it might be something else with our setup as well.

Here's an example of what the broken state looks like.

![Simulator Screenshot - iPhone 14 - 2023-09-12 at 13 12 53](https://github.com/ekazaev/ChatLayout/assets/2036378/fbfcfd46-a512-4a69-b5d2-8c7e476dd979)

**Comment by donnywdavis** [comment]
I had a look through the example app, and as you mentioned, I think that it might be related to the collection view setup. I was already thinking that, but couldn't figure out what would be wrong. So, we use `lazy var` to define our properties for the UI, but I noticed in the example app that you are creating it in `viewDidLoad`, which is different from our setup.

Here's how we have the layout and collection view defined.
```
private lazy var layout: CollectionViewChatLayout = {
        let layout = CollectionViewChatLayout()
        layout.settings.interItemSpacing = .baseGridValue(times: 3)
        layout.keepContentOffsetAtBottomOnBatchUpdates = true
        layout.delegate = self
        return layout
    }()

    private lazy var collectionView: UICollectionView = {
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collectionView.isPrefetchingEnabled = false
        collectionView.contentInset = .init(
            top: .baseGridValue(times: 6),
            left: .baseGridValue(times: 3),
            bottom: Self.bottomContentInset,
            right: .baseGridValue(times: 3)
        )
        collectionView.alwaysBounceVertical = true
        collectionView.keyboardDismissMode = .interactive
        collectionView.delegate = self
        collectionView.translatesAutoresizingMaskIntoConstraints = false
        return collectionView
    }()
```

I think that this would explain it, since the example app is initializing and setting up the collection view on screen launch, but our setup is only defining the collection view when it is first accessed, which could lead to the first access having the incorrect frame since it is not completely configured yet. 🤔

**Comment by ekazaev** [comment]
Yeah. Then the UICollectionView will be properly placed only when the container view controller that positions it. In general I suggest you to start any interaction with the view in/after the first call of viewDidLayoutSubviews.

Similar effect you can notice when you are pushing the view into the navigation controller for example. UICollectionView is not being yet adjusted by the UINavigationController to compensate the height of its navigation bar and so on. So it may incorrectly position it cells as the anjustedContentInset are not yet setup properly at the moment when ChatLayout calculates the offsets from the bottom.

**Comment by donnywdavis** [comment]
Thanks for the help in getting to the root cause of the issue. I was too deep into it, debugging, and couldn't see the forest for the trees. 😂

**Comment by ekazaev** [comment]
@donnywdavis No problem at all. Ill close the issue. But feel free to reopen it or create a new one if you'll have further issues.
