### ISSUE TITLE
Audio message 

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#55]
Hi, will you consider adding audio messages to the example?

**Comment by ekazaev** [comment]
@ElrB Hi,

TBH I havent planned to do so, it goes outside of the core functionality of the library. But I saw how it was done in other projects and there are no limitations to do so. The only thing you need to remember that cells are being reused so you can only use them as a representation of the current state of the app, but you can not store the state in them. So you need to create a separate manager that handles your audiomessages that downloads them/plays them/knows what message to play next and so on. And this manager should broadcast its state and your audio message cells should listen to this information using the audioMessageId they represent and update it state accordingly. There is no limitation there from the ChatLayout side.

Best of luck.

**Comment by ElrB** [comment]
@ekazaev Hi,

Thanks for the quick reply.
I will highly appreciate it if you can point me to an exemplary project which has this functionality in it. 
I know I can probably find it if dig deeper, but where in the example app can I stop the auto generated messages from being produced upon app open?

Thanks a lot.

**Comment by ekazaev** [comment]
@ElrB Unfortunately, I wont be able to point you to such project. I saw it in the projects I worked on but they are not open source :( I just can assure you that it is possible.

**Comment by ekazaev** [comment]
@ElrB In the Example app in the `DefaultRandomDataProvider` use those flags: 
```swift
    private let enableTyping = false
    private let enableNewMessages = false
    private let enableRichContent = false
```

**Comment by ElrB** [comment]
@ekazaev Thank you for the assistance.
