### ISSUE TITLE
chat layout blinking

### ISSUE THREAD

**Issue by SongSeoYoung** [ekazaev/ChatLayout#57]
Hello. 
There seems to be a bug that causes cells to blink in certain situations while using the chat layout.

Based on the sample app code provided, I tested it as follows (Tested after removing the automatically repopulate code)

Note: 
- `keepContentOffsetAtBottomOnBatchUpdates` must be set to true 
- Message in the first cell must be relatively short, and the text in the second message cell must be a relatively long message.
- The first cell of the second section must be the same as the first cell of the first section.   

```swift
let uuid = UUID()
let originMessage = Cell.message(.init(id: uuid, data: .text("short text message / shor text message / short text message / short text message / short text message / shor text message / short text message / short text message"), owner: User(id: 0), type.incoming), bubbleType: .normal)
let fristSectionModel = [Section(id: 0, title: "1", cells: [originMessage])]

DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(300)) { [weak self] in
    self?.processUpdates(with: fristSectionModel, animated: true, requiresIsolatedProcess: false)
}

let longMessage = Cell.message(.init(id: UUID(), data: .text("long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message/ long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message/ long text message / long text message / long text message / long text message / long text message / long text message / long text message / long text message"), ownerUser(id: 0), type: .incoming), bubbleType: .normal)
let secondSectionModel = [Section(id: 0, title: "1", cells: [originMessage, longMessage])]

DispatchQueue.main.asyncAfter(deadline: .now() + .milliseconds(1000)) { [weak self] in
    self?.processUpdates(with: secondSectionModel, animated: true, requiresIsolatedProcess: false)
}
```

If you configure the code as above and build it, the first cell blinks as shown in the video below.
https://github.com/ekazaev/ChatLayout/assets/42825223/65fd8b4d-8505-43c3-ac3b-f6eb5ebc3388

When debugging, the `public override func prepare(forCollectionViewUpdates updateItems: [UICollectionViewUpdateItem])` function is called and the state changes to `.afterUpdate`. When calculating the height of the controller, the state is calculated as the `afterUpdate` value, and the statement below becomes true and blinks.
```swift
 if heightDifference != 0,
           (keepContentOffsetAtBottomOnBatchUpdates && controller.contentHeight(at: state).rounded() + heightDifference > visibleBounds.height.rounded()) || isUserInitiatedScrolling,
           isAboveBottomEdge {
            context.contentOffsetAdjustment.y += heightDifference
            invalidationActions.formUnion([.shouldInvalidateOnBoundsChange])
        }
```

Please check this bug. 
Thank you.

**Comment by ekazaev** [comment]
@SongSeoYoung 

Hi, Ill check it out. 

The sections were not really tested as I always advice agains using sections for chat UI (See README as well). The only thing I must admit is that I am quite busy this days so If you have the solution - please feel free to create a PR. Ill check it out.

**Comment by ekazaev** [comment]
@SongSeoYoung 

Hi. Thank you for the edge case. It will be solved in the next release. I did a big rewrite there but it should be released soon.
![fix1](https://github.com/ekazaev/ChatLayout/assets/20243258/cc3d0c35-dc06-48a2-a85b-e285bada9d2d)
