### ISSUE TITLE
Can you write an example where inputBarView is a subview?

### ISSUE THREAD

**Issue by std-s** [ekazaev/ChatLayout#59]
hi,
Do you have time to write an example where inputBarView is a subview?
I tried to rewrite the current demo, but the effect was not very satisfactory.

**Comment by ekazaev** [comment]
@std-s Hi,

Unfortunately I wont have time anytime soon. I suggest you to try to use `keyboardLayoutGuide` as it may simplify the task.

**Comment by std-s** [comment]
👌
