### ISSUE TITLE
transitioning into the chat interface from the conversationList page is slow

### ISSUE THREAD

**Issue by 520xiaopohai** [ekazaev/ChatLayout#61]
Hello developer,

ChatLayout elegantly implements the layout of complex interfaces and offers smooth sliding. However, I've noticed that transitioning into the chat interface from the conversationList page is slow, even though the time taken to fetch data from the database is minimal.

Upon testing, I found that commenting out the line // KeyboardListener.shared.add(delegate: self) speeds up the display of the chat list. Alternatively, data displays quickly when pushing the conversationList controller with self.navigationController?.pushViewController(chatViewController, animated: false). But presenting the interface without animation feels awkward.

I've reviewed other issues such as:

https://github.com/ekazaev/ChatLayout/issues/51
https://github.com/ekazaev/ChatLayout/issues/40
Could you provide some optimization guidance?

Thank you.

https://github.com/ekazaev/ChatLayout/assets/10045191/f567ab0d-7eb2-41b6-ba57-ca6ebe9cbcb1

[ChatViewController.swift.zip](https://github.com/ekazaev/ChatLayout/files/13213449/ChatViewController.swift.zip)

**Comment by ekazaev** [comment]
@520xiaopohai Hi, thank you for the question. 

Unfortunately I have nothing to add except what I already said here https://github.com/ekazaev/ChatLayout/issues/51 The issue you are expecting is related to fact that you are populating the initial messages asynchronously. So it is absolutely normal behaviour what you see on the vide provided. There is an pushing animation curve and later the input view presentation curve. You **must** populate messages **synchronously** before you start the pushing animation. I have nothing to add here except you need to follow everything said here https://github.com/ekazaev/ChatLayout/issues/51#issuecomment-1582457608 There is a gif provided showing that if you follow the instruction - everything is fine. 

Unfortunately, I dont have time to write an example code.

**Comment by ekazaev** [comment]
@520xiaopohai 
I checked the code you provided
<img width="558" alt="Screenshot 2023-10-31 at 14 02 41" src="https://github.com/ekazaev/ChatLayout/assets/20243258/14649854-3565-4f90-b374-693e88afeef8">

Everything said above is valid. `loadInitialMessages` is asynchronous function. it must be like 
```swift
let sections = self.chatController.getInitialMessages()
...
```

**Comment by 520xiaopohai** [comment]
"good news Currently, I've modified the loadInitialMessages method to synchronously return the sections' values. It feels faster than the previous interface. As I'm fetching data from a Firebase database, it's challenging to handle the results synchronously. I tried using semaphores, but occasionally the UI would freeze. To circumvent this, I now pass in the initial data externally. However, I believe this is unrelated to another issue I'm experiencing: when transitioning from the conversationList to the ChatViewController, there is a noticeable jitter in the conversationList. Could you advise on what might need adjustment to address this jitter?"

I push the viewController like this
`ChatViewControllerBuilder().build(chatWith: conversation.conversation.userIDs.last ?? "", conversation: conversation.conversation, chatTitle: conversation.user?.name ?? "") { chatvc in
                    if let msgViewController = chatvc {
                        self.navigationController?.pushViewController(msgViewController, animated: true)
                    }
}`

I'm genuinely impressed with this framework, and it's been incredibly useful. I'd hate to abandon its use due to this minor flaw. I sincerely hope you can help address this issue. Thank you once again for your assistance and your outstanding work

the jitter is like this , a lillte shake in the video
https://github.com/ekazaev/ChatLayout/assets/10045191/f782bab8-2697-4d52-ad8c-3ee4fd6e4d21
[未命名文件夹.zip](https://github.com/ekazaev/ChatLayout/files/13222760/default.zip)

**Comment by 520xiaopohai** [comment]
![SCR-20231101-ksmx](https://github.com/ekazaev/ChatLayout/assets/10045191/78f7dd72-02bd-4343-80e8-d0103dc37756)
and the instruments is like this

**Comment by ekazaev** [comment]
@520xiaopohai It is hard for me to say what is the reason for jittering on your video. Youll have to find out it yourself. It feels like you somehow manage to affect UINavigationController push animation. But you got the idea right. 
Returning to the instruments screenshot - you can see that what takes time is layoutSubviews of the collection view. It has nothing to do with the ChatLayout method restoreContentOffset. So to improve the situation here you need to optimise the cell structure. One more thing I can suggest here - make sure that you are using instruments in release build on the real device. Container views provided with the library use swift generics and they are not performing well in Debug builds. 
I can only assure you that this library is used in the various apps in production and if everything is implemented correctly -  there are no noticeable performance issues related to the library itself.

**Comment by 520xiaopohai** [comment]
thank you~ I will try to make it

**Comment by ekazaev** [comment]
@520xiaopohai If you send me the view controllers code I can have a look and may be I can point you out what is the reason of jittering.

**Comment by 520xiaopohai** [comment]
[chatFiles.zip](https://github.com/ekazaev/ChatLayout/files/13263793/chatFiles.zip)
Ekazaev, your enthusiasm is truly commendable. I would also be delighted to receive your assistance. My session controller is implemented using ConversationViewController, and the chat window is created with `ChatViewControllerBuilder().build(chatWith: chatId, conversation: conversation.conversation, chatTitle: conversation.user?.name ?? "") { chatvc in
if let msgViewController = chatvc {
self.navigationController?.pushViewController(msgViewController, animated: true)
}
}`

**Comment by ekazaev** [comment]
@520xiaopohai Sorry for the delay I was busy. I do not see anything suspicious in your view controller code so I cant really point you out to the problem without being able to run this code.

**Comment by 520xiaopohai** [comment]
It's okay, I don't have time to make a runnable demo. I will follow up on this issue when I have time. If it can be simplified into a runnable demo, I will open this issue again. Thank you.
