### ISSUE TITLE
Forgot to use self. in closure

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#62]
Please fix minor below in next update.

**Comment by ElrB** [comment]
![Screenshot 2023-11-14 at 7 13 25 PM](https://github.com/ekazaev/ChatLayout/assets/66596779/3aa142b3-3ce5-4618-91ce-6b72821900b5)

**Comment by ekazaev** [comment]
@ElrB Thank you for the issue. 

Self is not forgotten there - The library was updated to swift 5.9 syntax and it is not required when the self is "strongified" in the closure. I would recommend to update your compiler settings when possible or create a temporary fork and fix it yourself until youll be able to switch to the newer swift compiler version in your project. Xcode 15 is already out for a while and I wont be able to support 2 different syntaxes simultaneously.

**Comment by ekazaev** [comment]
@ElrB Ill close this issue. If you have something to add please reopen it.
