### ISSUE TITLE
PDF cells 

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#63]
Hi ekazaev, 

Can you kindly add pdf cells to example app. Small gift to us for 2024 😉. It has been hard to do using MessageKit, but I think with the flexibility of ChatLayout, it’s pretty doable, but want your way. Thanks.

**Comment by ekazaev** [comment]
Hi @ElrB 

And happy new year. 

I do not fully understand what you mean PDF cell? Cell that opens a PDF file? It is fairly simple imho. The question is how do you want to look it in the chat. I never really touched the PDFkit. If it can generate a preview (and I assume it does) - just generate it and follow the path of URL or Image cells.

**Comment by ekazaev** [comment]
@ElrB Ill close the issue. Feel free to reopen it if you have something to add.
