### ISSUE TITLE
Include replica of iMessage curved lines connecting replies

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#64]
Hi @ekazaev 

Do you mind including a replica in example app of how iMessage connect reply messages. Just a basic example of it.
Below is a screenshot from my app with blue line showing how I would like to draw the line. The app is based off the example app.

![image_6487327](https://github.com/ekazaev/ChatLayout/assets/66596779/c0845b5d-2e47-4599-8e27-abd26f30f8ad)

iMessage example:

![jpeXf](https://github.com/ekazaev/ChatLayout/assets/66596779/b9eedaf5-b18e-4a31-8f8d-a47411f0a9ad)

**Comment by ekazaev** [comment]
@ElrB Hi. 

I have the feeling that they are using some kind of even more extended collection layout to be able to do so. You wont be able to achieve it using `ChatLayout` unfortunately. 
Yes, you can split an image into chunks and try to assemble them like a mosaic in the neighbouring cells. But it will look fine only in static. With any animation this mosaic will visualise that it consists of pieces. So I suggest you to review your UI rather than trying to achieve that effect. Especially I find it questionable from the UX point of view.

**Comment by ElrB** [comment]
I agree, positioning through multiple cells is out of the question. No need for it. However, demonstrating that the replying message is connected to the message cell right above it is necessary, in my opinion. Maybe using horizontal stack view to hold the curved line (left side), then bubble view (right side). But again, I think only you can do it properly man. Very challenging for me.

**Comment by ElrB** [comment]
Thanks for the information.

However, I am struggling. Not sure of where to create the stack view that holds the curved line view and reply bubble. Remember my app is based off the example app code, and I don’t fully understand how the cell is actually created. In data source, we call e.g createTextMessageCell(), but am not sure where the cell class is. 

So basically, my question is just where you would create the stack view, in the createCell method or? 

Thanks.

**Comment by ekazaev** [comment]
@ElrB 

If you are relying on the code from the Example app. Then Id suggest you to modify `MainContainerView`. I assume that you want to have a vertical stack view where `BezierMaskedView<CustomView>` is.

You can place there whatever you want in whatever order you want:
<img width="565" alt="Screenshot 2024-01-31 at 11 03 17" src="https://github.com/ekazaev/ChatLayout/assets/20243258/316c3700-832e-41d1-97ba-914756cb47b7">

```
diff --git a/Example/ChatLayout/Chat/View/Other/MainContainerView.swift b/Example/ChatLayout/Chat/View/Other/MainContainerView.swift
index 834fd36..1116d29 100644
--- a/Example/ChatLayout/Chat/View/Other/MainContainerView.swift
+++ b/Example/ChatLayout/Chat/View/Other/MainContainerView.swift
@@ -27,7 +27,7 @@ final class MainContainerView<LeadingAccessory: StaticViewFactory, CustomView: U
     }
 
     var customView: BezierMaskedView<CustomView> {
-        containerView.customView
+        messageContainer
     }
 
     var statusView: TrailingAccessory.View? {
@@ -56,7 +56,9 @@ final class MainContainerView<LeadingAccessory: StaticViewFactory, CustomView: U
         }
     }
 
-    private(set) lazy var containerView = CellLayoutContainerView<LeadingAccessory, BezierMaskedView<CustomView>, TrailingAccessory>()
+    private lazy var messageContainer = BezierMaskedView<CustomView>(frame: bounds)
+
+    private(set) lazy var containerView = CellLayoutContainerView<LeadingAccessory, UIStackView, TrailingAccessory>()
 
     private weak var accessoryOffsetConstraint: NSLayoutConstraint?
 
@@ -83,6 +85,14 @@ final class MainContainerView<LeadingAccessory: StaticViewFactory, CustomView: U
             containerView.bottomAnchor.constraint(equalTo: layoutMarginsGuide.bottomAnchor)
         ])
 
+        let quoteView = UIView()
+        quoteView.translatesAutoresizingMaskIntoConstraints = false
+        quoteView.heightAnchor.constraint(equalToConstant: 50).isActive = true
+        quoteView.backgroundColor = .red
+        containerView.customView.addArrangedSubview(quoteView)
+        containerView.customView.addArrangedSubview(messageContainer)
+        containerView.customView.axis = .vertical
+
         accessoryView.translatesAutoresizingMaskIntoConstraints = false
 
         updateOffsets()
@@ -105,7 +115,7 @@ final class MainContainerView<LeadingAccessory: StaticViewFactory, CustomView: U
            !avatarView.isHidden {
             avatarView.transform = CGAffineTransform(translationX: -((avatarView.bounds.width + accessorySafeAreaInsets.left) * swipeCompletionRate), y: 0)
         }
-        switch containerView.customView.messageType {
+        switch messageContainer.messageType {
         case .incoming:
             customView.transform = .identity
             customView.transform = CGAffineTransform(translationX: -(customView.frame.origin.x * swipeCompletionRate), y: 0)
```

**Comment by ElrB** [comment]
Thank you so much @ekazaev, really helpful for the community. 
However, what about the curved line that connect the quote message to reply message. For instance, placing the red box as incoming on the left and reply message on the right then placing a connecting image (curved line) somewhere suitable. 

Thanks.

**Comment by ekazaev** [comment]
@ElrB if you want it to do like on the screenshot you have at the beginning - use the same stack view from the snippet above just make it horizontal and add the image of the curved line there. And render a quote as a separate cell. Probably that will be the easiest approach. 

Or use the `SwappingContainerView` provided with the library if your image can appear both on the left or right side of the cell depending if its incomming or outgoing and change it `distribution` accordingly.

**Comment by ElrB** [comment]
@ekazaev I will probably go with the horizontal stack view approach as I currently use 2 cells to represent replies (although not the best).

I am just concerned about the distribution in the h stack view. In your v stack view screenshot, it looks like the stack's width is the same as the bubble's? If its the case then in the h stack, there won't be space for the curved line.

Also we have been talking about image to represent the curved line, but I think it should be a custom drawn view? Image will allow better performance but not sure if it will scale/stretch well to fit different space sizes.

**Comment by ElrB** [comment]
Okay. Let me try out these solutions and return to update you.

**Comment by ekazaev** [comment]
@ElrB Ill close the issue. Feel free to reopen it if you have more questions.
