### ISSUE TITLE
chat container refresh in some strange conditions

### ISSUE THREAD

**Issue by fukemy** [ekazaev/ChatLayout#68]
Hi, I just notice the chat container reload again in some case that user doesnt want. Such as when I press the link, then back to the app, then I see the chat refresh, you can see the video attach below:

https://github.com/ekazaev/ChatLayout/assets/8202437/f5c5447e-7f7e-48ac-bb43-dad9e9826d22

**Comment by ekazaev** [comment]
@fukemy Sorry last time I tested something I commited the use of memory only caches in the example app. 
To have the correct behaviour - it needs to be like this.
<img width="1068" alt="Screenshot 2024-03-06 at 12 09 38" src="https://github.com/ekazaev/ChatLayout/assets/20243258/842b5cba-4424-45da-8798-c46b99c838ca">

Updated
