### ISSUE TITLE
Enabling UICollectionView prefetch

### ISSUE THREAD

**Issue by heoblitz** [ekazaev/ChatLayout#73]
Hello @ekazaev Firstly, thank you for creating this nice open-source project.

I noticed that isPrefetchingEnabled for the collection view is being blocked in debug mode.

However, it seems that the bug reported at https://openradar.appspot.com/40926834 is not reproducible in the Example app, iOS 17.4.1, and iOS 15.1 environments.

When setting isPrefetchingEnabled to true in the Example app

<img src="https://github.com/ekazaev/ChatLayout/assets/25315898/badf9145-df7a-4112-843a-46247efe8679" width="300">

Attempting to reproduce the reported bug in the Example app

<img src="https://github.com/ekazaev/ChatLayout/assets/25315898/800a0581-d6f2-4414-8a66-7b0a49e58f75" width="300">

Therefore, I thought it would be beneficial to either remove the preconditionFailure or add isPrefetchingEnabled to CollectionViewChatLayout so that developers can control it, in order to utilize the performance optimization of prefetching.

```swift
isPrefetchingEnabled = false

open override func prepare() {
    super.prepare()

    #if DEBUG
    if !isPrefetchingEnabled && collectionView.isPrefetchingEnabled {
         preconditionFailure("UICollectionView with prefetching enabled is not supported due to https://openradar.appspot.com/40926834 bug.")
    }
    #endif
}
```

If the above direction is okay, I'll try to raise the PR. If there's anything I'm missing, please let me know, thanks.

**Comment by ekazaev** [comment]
@heoblitz Hi, thank you for the issue.
Yeah, I just added that becasue I got few requests in the past when people used the ChatLayout from scratch and got interface jumpy. Feel free to create a PR and remove that check. Or wait a bit ill update the library myself.

**Comment by heoblitz** [comment]
Thank you for checking, @ekazaev I've submitted a simple PR.
