### ISSUE TITLE
Text messages bubble width changes after scrolling 

### ISSUE THREAD

**Issue by ElrB** [ekazaev/ChatLayout#75]
Hi @ekazaev 

Please see attached video. 
It looks like sometimes the width of some text messages changes after scrolling. My code is purely off the example app. 

https://github.com/user-attachments/assets/727279fb-13c1-46d7-b547-549801d7d56e

**Comment by ekazaev** [comment]
Hi @ElrB 

I can only suggest that you have the first time layout issue when the label or UITextView doesnt return correct width/height. Later when the cell size propogated again - it layouts correctly and returns correct size to the collection view. 

If your code is based on example app - it should be easy to reproduce it there. Modify it the same way and I can look after.

**Comment by ElrB** [comment]
Hi @ekazaev 

I forgot to mention that this issue only happens to one line text messages that have a width close to (viewPortWidth * MessageLayoutConstants.maxWidth).

Where should I check the preferredLayoutAttributesFitting? 

Thanks.

**Comment by ekazaev** [comment]
@ElrB  In the UICollectionViewCell

**Comment by ElrB** [comment]
Hi @ekazaev 

I check preferredLayoutAttributesFitting in createTextCell method like (hopefully I did check correctly) - 

if let layout = collectionView.collectionViewLayout as? CollectionViewChatLayout, let attributes = layout.layoutAttributesForItem(at: indexPath) {
            print("message: ", message.messageCoreInformation.message)
            print("attributes: ", cell.preferredLayoutAttributesFitting(attributes))
}

Below is a print out of the attributes before and after scrolling (same message that has issue)

Before - 

![Screenshot 2024-08-07 at 9 20 18 AM](https://github.com/user-attachments/assets/79722bf6-114e-44bf-bdab-d835b0be330f)

After - 

![Screenshot 2024-08-07 at 9 20 30 AM](https://github.com/user-attachments/assets/77238311-0074-4e59-8a9f-561d59acf211)

**Comment by ekazaev** [comment]
Well. On your video it seems opposite. But we see that the height 60 doesnt look like what you expect. What `preferredLayoutAttributesFitting` does if it is not modified is uses `systemLayoutSizeFitting` on the content view of your cell. And for some reason it gets the wrong size. I would check the constraints and so on. If you are using the `UIlabel` which I dont recommend - check that you are setting `preferredMaxLayoutWidth`. It is usually the issue with labels.
PS: But there is technically nothing to do with the collection view or layout. Collection view asks cell for its preferred size -> cell reports its preffered size -> collection view using the layout allocates it on the screen accordingly.

**Comment by ElrB** [comment]
Hi @ekazaev 

I figured viewPortWidth = layoutAttributes.layoutFrame.width was somehow not getting the correct width when view is first push onto screen. So I replaced it with private var viewPortWidth: CGFloat = ScreenSize.Width and solved the issue.


Lastly I just wanted your insight of what I could be doing wrong with how I present the chat view, because the animation is not good at all (please see attached video).

Below is the code on how I build the chat view. Thanks. Appreciated.

class ChatViewControllerBuilder {

    static let shared = ChatViewControllerBuilder()
    var vc: ChatViewController?
    var vc1: GroupChatViewController?
    
    func asyncBuild(with buildInstruction: BuildCoreInformation, launcher: UIViewController, tabBarHeight: CGFloat?) {
        let imagePickerPreview = ImagePickerPreviewCollectionVC(frame: CGRect(x: 0, y: 0, width: ScreenSize.Width, height: 260))
        let editNotifier = EditNotifier()
        let swipeNotifier = SwipeNotifier()
        
        let chatIdentityInforamtion = ChatIdentityInforamtion(
            senderId: buildInstruction.userId,
            receiverId: buildInstruction.receiverId,
            receiverName: buildInstruction.receiverName,
            chatRoomId: buildInstruction.chatRoomId
        )
        
        let dataProvider: DefaultDataProvider = DefaultDataProvider(
            chatRoomId: buildInstruction.chatRoomId,
            receiverId: buildInstruction.receiverId,
            recentChat: buildInstruction.recentChat
        )
        
        let messageController: DefaultChatController = DefaultChatController(
            chatIdentityInforamtion: chatIdentityInforamtion,
            dataProvider: dataProvider,
            imagePickerPreviewController: imagePickerPreview,
            userId: buildInstruction.userId,
            recepientIsMyContact: buildInstruction.recepientIsMyContact
        )
        
        let dataSource: DefaultChatCollectionDataSource = DefaultChatCollectionDataSource(
            editNotifier: editNotifier,
            swipeNotifier: swipeNotifier,
            reloadDelegate: messageController,
            editingDelegate: messageController,
            replySetupDelegate: messageController
        )
        
        let messageViewController: ChatViewController = ChatViewController(
            chatController: messageController,
            dataSource: dataSource,
            editNotifier: editNotifier,
            swipeNotifier: swipeNotifier,
            chatIdentityInforamtion: chatIdentityInforamtion,
            messageIdForScrollTarget: buildInstruction.messageIdForScrollTarget,
            recentChat: buildInstruction.recentChat,
            senderAvatarImage: buildInstruction.senderAvatarImage,
            receiverUserObject: buildInstruction.receiverUserObject,
            lockedChat: buildInstruction.lockedChat,
            dataProvider: dataProvider,
            imagePickerPreviewController: imagePickerPreview,
            inputBarCollectionVCHolder: imagePickerPreview
        )
        
        dataProvider.delegate = messageController
        messageController.delegate = messageViewController
        
        self.vc = messageViewController
        
        messageController.loadInitialMessages { [weak self] sections in
            guard let self = self, let vc = self.vc else { return }
            vc.initialSections = sections
            vc.loadInitialSections = false
            if let viewController = launcher as? ChatsTableViewController, let tabBarHeight = tabBarHeight {
                vc.tabBarHeight = tabBarHeight
                viewController.navigationController?.pushViewController(vc, animated: true)
                self.vc = nil
            }
        }
    }
}

override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        if inputBarView.superview == nil,
           topMostViewController() is ChatViewController {
            DispatchQueue.main.async { [weak self] in
                guard let self else { return }
                self.reloadInputViews()
            }
        }
        
        if isFirstAppearance {
            if loadInitialSections {
                currentControllerActions.options.insert(.loadingInitialMessages)
                chatController.loadInitialMessages { [weak self] sections in
                    guard let self else { return }
                    self.currentControllerActions.options.remove(.loadingInitialMessages)
                    self.processUpdates(with: sections, animated: true, requiresIsolatedProcess: false, forceAnimation: false)
                }
            } else {
                self.processUpdates(with: initialSections, animated: true, requiresIsolatedProcess: false, forceAnimation: false)
            }
            isFirstAppearance = false
        }
}


https://github.com/user-attachments/assets/cc056419-4528-4f6d-a63a-d243549baaa3

**Comment by ekazaev** [comment]
@ElrB It is not good enough solution. Because if you start to integrate your view into the split controller for ipad for example - it wont be a correct width.
It is normal that when the view controller is not yet appeared it doesnt know its correct size, that why collection view in it doesnt set values you expect.
You need to make sure you call something to ivalidate layout after the view got a coorect size.
