### ISSUE TITLE
Mutable capture of 'inout' parameter 'directlyMutableSections' is not allowed in concurrently-executing code

### ISSUE THREAD

**Issue by lucaslimapoa** [ekazaev/ChatLayout#76]
Trying to compile a project using `ChatLayout` on Xcode 16.1 breaks with the following error message: `Mutable capture of 'inout' parameter 'directlyMutableSections' is not allowed in concurrently-executing code`.

**Comment by ekazaev** [comment]
Thank you @lucaslimapoa 

ill check it out. Hopefully its not one of those issues “swift 6 is so safe that its not safe” 😂

**Comment by ekazaev** [comment]
@lucaslimapoa  should be fixed in 2.0.10 version. 
Thank you for pointing it out.
Please, feel free to reopen this issue if it is not enough.
