### ISSUE TITLE
keepContentOffsetAtBottomOnBatchUpdates add tolerance range

### ISSUE THREAD

**Issue by mschonvogel** [ekazaev/ChatLayout#9]
Hello @ekazaev 👋 Currently, the layout only scrolls automatically when you have scrolled all the way down. Can you add a configuration for a tolerance range? So that even if you are for example 100pt from the bottom of the Scrollview and a new message comes in, it still scrolls automatically?

**Comment by ekazaev** [comment]
@mschonvogel hi

I was thinking about it but I think iMessage behaves differently. It is controlled by the host during the sending or receiving the new message. Can you please describe the behavior with that tolerance?

**Comment by ekazaev** [comment]
@mschonvogel 
Is that what you expect to see when you say tolerance? 
https://user-images.githubusercontent.com/20243258/106735361-084f7d80-660c-11eb-94ff-07eae2d5d11d.mov

**Comment by mschonvogel** [comment]
@ekazaev The left screen should automatically scroll to the latest message here
https://user-images.githubusercontent.com/370839/106735887-105feb00-6615-11eb-9c70-02f8fdd3a1de.mov

**Comment by ekazaev** [comment]
Or do you mean that it should scroll fully to the bottom if the new message has come? 
It seems to me that it should be decided and implemented in the host app. For collection view layout it just a cell. IT does not distinguish them from each other. It can be a new message, it can be "Delivered/Read" bage change, typing indicator. So I think that if "new message comes" - the app knows that and can scroll to the new message if user is within some amount of pixels from the bottom.

**Comment by ekazaev** [comment]
@mschonvogel I see. Thanks. It seems to me like its an app responsibility tbh. And it seems that it is kinda easy to implement?

**Comment by mschonvogel** [comment]
Yes, I can implement that in the host app of course. But I thought that somehow makes sense since the layout already takes care of setting the content offset automatically

**Comment by mschonvogel** [comment]
I expect the collectionview to scroll if I'm like max 20points await from the bottom @ekazaev

**Comment by ekazaev** [comment]
Ist just sounds like it has logic inside. If new message -> Scroll, If typing indicator appears -> Dont, If we inserted "read" bage -> dont scroll. 

I understand you, but it is something that should be implemented in the host app. Or a framwork built arount ChatLayout. But not a layout itself.

**Comment by mschonvogel** [comment]
Okay, all right, I'll implement this myself 🙂

**Comment by ekazaev** [comment]
Sorry about that. 
I just see that if it will be in the layout you will have to implement the opposite logic in the host app:
If new message -> Set tolerance to 20px, If typing indicator appears -> Set tolerance to 0, If we inserted "read" cell -> Set tolerance to 0.

**Comment by mschonvogel** [comment]
I understand what you mean but I still disagree, which is not a problem 🙂. The case I want to cover here is: The user thinks they are at the end of the chat history, but they're not, because 10pt away. So I would expect scrolling for all inserts. typing indicator, state update etc.

**Comment by ekazaev** [comment]
I am just trying to find the right balance here :)
I use that layout in my work. And I remember (even though that was in the view controller) that I was scrolling down every time something appeared at the bottom. And it did not pas a QA because I got "Dont scroll user to the bottom every time a typing indicator appears"

**Comment by mschonvogel** [comment]
Yes, I understand the thinking of your QA department, but in that case, if you are only a few pixels off the bottom, I would still scroll automatically ☝️😀

**Comment by ekazaev** [comment]
Something like this will solve the issue in the example:
```
                                  completion: { _ in
                                      if self.collectionView.contentOffset.y > self.collectionView.contentSize.height - self.collectionView.frame.height + self.collectionView.adjustedContentInset.bottom - tolerance {
                                          self.scrollToBottom(completion: completion)
                                      } else {
                                          completion?()
                                      }
                                  },
```

**Comment by ekazaev** [comment]
Let me sleep with that thought. @mschonvogel 
I mean, I understand where are you coming from. The question is if `keepContentOffsetAtBottomOnBatchUpdates` is not enabled, but tolerance is set. Should it scroll to the top within that tolerance?

**Comment by ekazaev** [comment]
https://user-images.githubusercontent.com/20243258/106745387-ed373a80-6618-11eb-961c-b9a8ea0fd3a2.mov

**Comment by mschonvogel** [comment]
That looks good! I'd probably utilize an enum for that, maybe like so:

```swift
enum KeepContentOffsetAtBottomBehavior {
  case disabled
  case enabled(tolerance: CGFloat)
}

**Comment by ekazaev** [comment]
Ill think about it. I promise. But for now everything that comes into my head tells me against it.

**Comment by ekazaev** [comment]
I think it actually has sense to scroll to the bottom before anything appears if user within that tolerance to the bottom.
